### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by NJMD13** [SafiraaCute/OnlyProxyJoin-WDPE#1]
Hello good afternoon, sorry for interfering in the creation of your plugin.

But I saw the Poggit page that the plugin had an error and I wanted to help a little and solve it, in the following link is your plugin with the fix: [OnlyProxyJoin-WDPE FIX](https://github.com/IpodCraft/test)

I apologize in advance if my action bothers you.

and have a good evening

**Comment by AraaCuteUwU** [comment]
not annoying at all. Thank you for reporting and fixing the error
